version: "3.7"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    networks:
      - app_network
    env_file:
      .env-non-dev
    expose:
      - "5432"

  app:
    build:
      context: .
    container_name: fastapi_app
    entrypoint: sh -c "alembic upgrade head && cd src && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    command: pytest -v
    networks:
      - app_network
    env_file:
      .env-non-dev
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  app_network:
    name: app_network