services:
  db:
    image: postgres:15.1-alpine
    container_name: app_database
    env_file:
      - .env-non-dev

  fastapi:
    build:
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - .env-non-dev
    ports:
      - 8000:8000
    depends_on:
      - db
    command: /bin/bash -c "sleep 5 && python -m alembic upgrade head && python -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
