version: "3.7"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    networks:
      - app_network
    env_file:
      .env-non-dev
    expose:
      - "5432"

  app:
    build:
      context: .
    container_name: fastapi_app
    networks:
      - app_network
    env_file:
      .env-non-dev
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

networks:
  app_network:
    name: app_network
